### ISSUE TITLE
Invalid "clover" report

### ISSUE THREAD

**Issue by ivailop** [istanbuljs/istanbuljs#13]
The `clover` xml report (generated via `nyc report --reporter=clover`) appears to be invalid. 
Please consider [clover.zip](https://github.com/istanbuljs/istanbuljs/files/856487/clover.zip).

The following snippet illustrates the problems:
```
<coverage generated="1490037667659" clover="3.2.0">
  <project timestamp="1490037667660" name="All files">
    <metrics statements="446" coveredstatements="442" conditionals="278" coveredconditionals="264" methods="78" coveredmethods="78" elements="802" coveredelements="784" complexity="0" loc="446" ncloc="446" packages="1" files="9" classes="9">
      <file name="apk.js" path="/home/travis/build/testspace-open/dockerfilelint/lib/apk.js">
...
    </metrics>
  </project>
</coverage>
```

* the top level `metrics` has to be "inline" (i.e. has no children) but instead it wraps the whole content
* the content has to be wrapped in `package` tag

Expected output:
```
<coverage generated="1490037667659" clover="3.2.0">
  <project timestamp="1490037667660" name="All files">
    <metrics statements="446" coveredstatements="442" conditionals="278" coveredconditionals="264" methods="78" coveredmethods="78" elements="802" coveredelements="784" complexity="0" loc="446" ncloc="446" packages="1" files="9" classes="9"/>
    <package name="lib">
      <file name="apk.js" path="/home/travis/build/testspace-open/dockerfilelint/lib/apk.js">
...
    </package>
  </project>
</coverage>
```

**Comment by bcoe** [comment]
@ivailop I believe this should be fixed now, mind also confirming.

**Comment by hschott** [comment]
Problem still persists.

https://github.com/istanbuljs/istanbuljs/blob/ec871df8d8f9f692170aa40c092ceb79cbe4608c/packages/istanbul-reports/lib/clover/index.js#L91

This opens the 'metrics' and it will be closed when the xml-writer closes all elements.
It should be:
`this.xml.inlineTag('metrics', attrs);`

**Comment by dunklesToast** [comment]
> the content has to be wrapped in package tag

This was never addressed and is still an issue. Small example:
```
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1593505537305" clover="3.2.0">
  <project timestamp="1593505537305" name="All files">
    <metrics/>
    <file name="CloverCoverageParser.ts" path="/Users/tom/File.ts">
      <metrics/>
    </file>
  </project>
</coverage>
```
While this would be the correct output:
```
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1593505537305" clover="3.2.0">
  <project timestamp="1593505537305" name="All files">
    <metrics/>
      <package name="src">
          <file name="File.ts" path="/Users/tom/project/src/File.ts">
      </package>
      <metrics/>
    </file>
  </project>
</coverage>
```

|Package|Version|
|:---:|:---:|
|nyc|15.1.0|
