### ISSUE TITLE
Transformation error when instrumenting the same file is multiple concurrent processes

### ISSUE THREAD

**Issue by ajafff** [istanbuljs/istanbuljs#141]
The Windows CI of my project is failing intermittendly because of a transformation error (because of the output to `stderr` to be more precise).

For example : https://ci.appveyor.com/project/ajafff/wotan/build/1.0.268

```
Transformation error for C:\\projects\\wotan\\packages\\wotan\\src\\test.js ; return original code
EPERM: operation not permitted, rename 'C:\\projects\\wotan\\node_modules\\.cache\\nyc\\b02833cec8fc53deebd0f2490cfebdba_11.4.1.js.1850078834' -> 'C:\\projects\\wotan\\node_modules\\.cache\\nyc\\b02833cec8fc53deebd0f2490cfebdba_11.4.1.js'
Transformation error for C:\\projects\\wotan\\packages\\wotan\\src\\services\\default\\directory-service.js ; return original code
EPERM: operation not permitted, rename 'C:\\projects\\wotan\\node_modules\\.cache\\nyc\\d42708c875570eee94cf5796e9bd499e_11.4.1.js.886011032' -> 'C:\\projects\\wotan\\node_modules\\.cache\\nyc\\d42708c875570eee94cf5796e9bd499e_11.4.1.js
```

I use `nyc` to collect the coverage of my `ava` tests. The tests are run concurrently by default.

This error seems to only occur when running the tests in parallel. And I don't have the same issue on Linux or macOS.
The issue occurred when I had no `cache: true` in my `.nycrc.json` *and* after I enabled the cache.

I guess this is related to concurrent access to the same cache.

What information do you need to diagnose this issue?

---

My project is https://github.com/fimbullinter/wotan
To run the tests with coverage, you need to `yarn install` and `yarn compile` first and then `nyc yarn test`

**Comment by ehmicky** [comment]
I've tried with `nyc` `14.0.0` and it now seems to be working fine for me. Although it's hard to be 100% sure considering the problem appeared randomly. If it appears again, I will post a comment. Otherwise, if I don't post within a week, you can consider the problem solved for me.

@ajafff Is it the problem solved for you if you upgrade to `14.0.0`?

**Comment by ehmicky** [comment]
Never mind, this is still happening: https://travis-ci.org/ehmicky/unix-permissions/jobs/523407051

**Comment by coreyfarrell** [comment]
This appears to be an upstream issue, possibly node.js itself.  caching-transform uses write-file-atomic to save cache files, see npm/write-file-atomic#28.

I'm open to suggestions but I don't know if this one can be solved.  The only potential work-around would be to set `cache: false` on nyc.  Maybe nyc@15.0.0 could make the default `cache: false` for Windows only (still default `cache: true` for other platforms).  This would not prevent `.nycrc` from having `cache: true` to force it on Windows.

CC @bcoe @JaKXz

**Comment by ehmicky** [comment]
Thanks for looking into it!
Yes that npm issue might be the problem. 
I'm going to try to use `cache: false` and report if this works. The bug appears randomly, so it might take few days to manifest in my CI builds.

**Comment by ehmicky** [comment]
When using `cache: false`, another error is still thrown. But this time it is:

```
`Transformation error for C:\\Users\\travis\\build\\ehmicky\\unix-permissions\\build\\src\\bin\\main.js ; return original code␊
EBADF: bad file descriptor, close`
```

This error was also reported in https://github.com/npm/write-file-atomic/issues/28, so this does seem to be the cause of this issue.

**Comment by coreyfarrell** [comment]
This is odd as `cache: false` **should** disable caching-transform, so I'm not sure how this can still happen.  Also for reference I use `nyc ava` on many of my own projects and have never had this issue.

**Comment by ehmicky** [comment]
I implemented it wrong, and `cache: true` was actually passed. With `cache: false`, it seems to work now (although I need to wait for few days since the bug is somewhat random).

I also don't have that issue with most of my projects that use `nyc ava` except [one that has about 3000 small CPU-bound unit tests run in parallel](https://travis-ci.org/ehmicky/unix-permissions/jobs/529252003).

Using `cache: false` does make tests much slower, so I'm wondering if there is another way to solve the problem solved by `write-file-atomic`? I am trying to understand what this problem is, and what I understand so far is:
  1) Istanbul hooks into `require()` and `vm.runIn[This]Context()` in order to instruments files.
  2) The same file might be instrumented twice if it's required by two different files.
  3) Files instrumentation is cached in `node_modules/.cache/nyc/`
  4) Because of 2) and 3), there might be a concurrency issue where a file is currently being instrumented, while another is checking if it's already in the cache. The cached file might be partially written (before I/O writes are not atomic), which would be a problem.
  5) `write-file-atomic` fixes this by writing cached files into a different directory, then calling `fs.rename()` once the file is entirely written.
  6) The solution 5) has issues on Windows because `fs.rename()` themselves might create concurrency issues when two `fs.rename()` are performed at the same time.

Just trying to understand the problem here: did I get anything wrong?

**Comment by coreyfarrell** [comment]
8 minutes vs 38 minutes... wow.  That's quite a bit.  I think this cancels my plan to set `cache: false` by default on Windows.  I think you understand the issue.

In theory you could create an npm pretest script that initializes the cache.  This would be done by running `nyc ./require-everything.js` where require-everything.js is a script such as:
```js
const nycConfig = JSON.parse(process.env.NYC_CONFIG);
const testExclude = require('test-exclude')(nycConfig);

testExclude.globSync().forEach(source => {
  require(source);
});
```

This should cause every file to be instrumented in a single process which runs before your tests.  Note that the `nyc ./require-everything.js` command must have the same command-line options as you use when you run your tests to ensure everything works the same.  So this `pretest` script would create an `.nyc_output` with some coverage, but when you run your actual tests that will get reset (as long as you don't pass `--no-clean` to nyc).  Important thing is that `node_modules/.cache/nyc` from the pretest step would remain so in theory no cache files would need to be created during running of ava.

Also beware if any of your sources have side-effects during `require()`.  For this reason I'm unsure it's even possible for nyc to get a 'pre-cache' option.

**Comment by ehmicky** [comment]
Actually it's more like: 22 minutes with `nyc --cache ava --serial` and 38 minutes with `nyc --no-cache ava` (note that removing `--serial` should speed up the tests). Windows is just much slower on Travis than Linux and Mac, hence the difference with 8 minutes on those OS.

Thanks for the workaround, I will try it out.

I think the real fix for this issue is to have https://github.com/npm/write-file-atomic/issues/28 fixed. That's a pretty complex one though.

What about the following workaround: if `write-file-atomic` fails with a `EPERM` permission, silently do not propagate the error:
  - if a cache has not been written, code should still work. The only difference is that instrumentation won't be cached for that file. Next time the file is instrumented, caching might succeed then.
  - some extra checks could be made be sure that `EPERM` is due to that bug, and not to the cache directory not being writable.

Would this work?

**Comment by coreyfarrell** [comment]
I'm not sure.  In theory if we have this failure then the code should already be cached, unless we're getting a legit EPERM error.  I'm thinking that it might be better to implement loop that will retry up to 3 times.  If `writeFileAtomic` fails then hopefully the file exists because of the other process we conflicted with, then we can simply read that file / return the contents.

I'm against having caching-transform silently swallow errors.

**Comment by ehmicky** [comment]
Yes you're right that seems like a better solution.

**Comment by coreyfarrell** [comment]
@ehmicky I've been informed this write-file-atomic issue might be a regression in `>2.3.0`.  I've pushed a branch https://github.com/istanbuljs/caching-transform/tree/pin-write-file-atomic which pins write-file-atomic to the version which (potentially) does not have the issue.  Could you test with this?  You should be able to setup your project with devDependencies for `"nyc": "^14.1.1"` and `"caching-transform": "istanbuljs/caching-transform#pin-write-file-atomic"`.  In theory the caching-transform git branch should match the version requested by nyc.  Maybe add a pretest script to `npm ls write-file-atomic` so your CI will verify the desired version is installed.

**Comment by ehmicky** [comment]
Thanks for checking this out!

This version pinning does not resolve as expected:

```bash
npm ls caching-transform
gulp-shared-tasks@0.27.57 /home/ehmicky/gulp-shared-tasks
├── caching-transform@3.0.2  (github:istanbuljs/caching-transform#c832db48c670a104a36d28aa3bf7ea7eb888395a)
└─┬ nyc@14.1.1
  └── caching-transform@3.0.2  deduped (github:istanbuljs/caching-transform#c832db48c670a104a36d28aa3bf7ea7eb888395a)
```

Somehow `nyc > caching-transform`  resolves to `3.0.2` hash `c832db48c670a104a36d28aa3bf7ea7eb888395a`.

**Comment by coreyfarrell** [comment]
That is actually expected, caching-transform on `git` still has `"version": "3.0.2"` in package.json.  Getting npm to dedupe caching-transform for nyc is the goal.  That is why I recommended checking `npm ls write-file-atomic`.  BTW the hash you list is the expected git commit from the branch.

**Comment by ehmicky** [comment]
Oh you're right.

Unfortunately the bug [is still happening](https://travis-ci.org/ehmicky/unix-permissions/jobs/530831458) even with [`write-file-atomic@2.3.0`](https://github.com/ehmicky/unix-permissions/blob/652e7cbc7872432010dcd091932f3849f98f1bcf/package-lock.json#L2203).

**Comment by coreyfarrell** [comment]
Thanks for testing.  Please give it a try with `istanbuljs/caching-transform#unbreak-windows` (https://github.com/istanbuljs/caching-transform/tree/unbreak-windows).

**Comment by ehmicky** [comment]
This might do the trick. I have tried running CI tests 4 times, and no errors yet. I will keep trying through the weekend, but it seems like this fixes the issue :)

**Comment by ehmicky** [comment]
I have restarted the job about 15 times, and it seems to be working!

**Comment by coreyfarrell** [comment]
This issue can be temporarily worked around by configuring your package.json with a development dependency on  `"caching-transform": "istanbuljs/caching-transform#1689877"`.  Note that this updated version requires node.js 8.  This fix will be included directly with nyc@15.  Please follow https://github.com/istanbuljs/nyc/issues/1104 for updates about the new release.

**Comment by ehmicky** [comment]
Thanks @coreyfarrell!
