### ISSUE TITLE
Incorrect branch coverage when using implicit else post #633

### ISSUE THREAD

**Issue by alan-agius4** [istanbuljs/istanbuljs#670]
Post #633 the implicit else is not being counted as a branch.

**Before**
![Screenshot 2022-02-08 at 10 10 18](https://user-images.githubusercontent.com/17563226/152954589-dd2f4235-04b0-48d6-8552-5e69149d0252.png)
```json
{
  "branchMap": {
    "0": {
      "loc": {
        "start": { "line": 2, "column": 2 },
        "end": { "line": 5, "column": null }
      },
      "type": "if",
      "locations": [
        {
          "start": { "line": 2, "column": 2 },
          "end": { "line": 5, "column": null }
        },
        {
          "start": { "line": 2, "column": 2 },
          "end": { "line": 5, "column": null }
        }
      ]
    }
  }
}
```
**After**
![Screenshot 2022-02-08 at 10 11 07](https://user-images.githubusercontent.com/17563226/152954717-1f180d57-b982-42dc-b91d-27eab09452cf.png)

```json
{
  "branchMap": {
    "0": {
      "loc": {
        "start": { "line": 2, "column": 2 },
        "end": { "line": 5, "column": null }
      },
      "type": "if",
      "locations": [
        {
          "start": { "line": 2, "column": 2 },
          "end": { "line": 5, "column": null }
        }
      ]
    }
  }
}
```
**Reproduction**

https://github.com/alan-agius4/coverage-issue-istanbul

```
git clone https://github.com/alan-agius4/coverage-issue-istanbul.git
cd coverage-issue-istanbul
yarn
yarn test
```

Reported in Angular CLI: https://github.com/angular/angular-cli/issues/22652

**Comment by bcoe** [comment]
This was hopefully fixed by:

https://github.com/istanbuljs/istanbuljs/pull/663

Are you able to test against the latest release of the instrumenter?

CC: @adrian-burlacu-software

**Comment by alan-agius4** [comment]
@bcoe, I am using the latest version and the issue is still persists.

**Comment by luismartinez85** [comment]
@bcoe, I am using the latest version and the issue is still persists.

**Comment by phyr0s** [comment]
Using lastest version and not working

**Comment by adrian-burlacu-software** [comment]
@bcoe @alan-agius4 @phyr0s 

Ok so I originally fixed the coverage map in #633 because of the erroneous output.
Then, being a new contributor I figured downstream reporting would be updating by the rest of the genius crowd like yous guys :)
Tried and succeeded to fix #663 talks about Implicit else and **not a single if statement with no subsequent else like your example**.

Now based on the help I've been getting from @bcoe  on publishing #673 and #675 I think we're both busy. I'm certainly not fixing this for a good two months so I'd consider picking up the genius quill and fix this case in the downstream two.

Cheerio, fellow collaborator ;)

**Comment by phyr0s** [comment]
@adrian-burlacu-software hello. I tried lastest version but branch coverage is broken.

**Comment by adrian-burlacu-software** [comment]
@bcoe @alan-agius4 @phyr0s @luismartinez85 @djok1

Just now I added the necessary placeholder to fix this in the reporting in pull #679.

When this gets released, I'll watch, but two things need to happen:
- bcoe needs to merge the release branch
- bcoe needs to approve the release branch. (Still waiting on this step in pull #673 )

**Comment by phyr0s** [comment]
@bcoe when you can check the @adrian-burlacu-software  job? Thanks

**Comment by adrian-burlacu-software** [comment]
@bcoe 
Just released Fast-Fuzz 4.0 that can pretty much fuzz any TypeScript: https://www.npmjs.com/package/fast-fuzz
That might come in handy here.

**Comment by bcoe** [comment]
This is hopefully fixed by https://github.com/istanbuljs/istanbuljs/pull/679

**Comment by antch** [comment]
I don't think this is fixed...

```
$ npm ls istanbul-reports
ema-web@0.0.0 /Users/antch/angular
├── istanbul-reports@3.1.5 
└─┬ karma-coverage@2.0.3
  └── istanbul-reports@3.1.5  deduped
```

![image](https://user-images.githubusercontent.com/4552169/184395382-bc48fa37-343b-476c-a34e-67a53aab5ab5.png)

**Comment by acieroid** [comment]
I can confirm that it is not fixed, after upgrading to Angular 14 and reproducing the same as the initial bug report (https://github.com/angular/angular-cli/issues/22652), coverage is still incorrectly computed.

**Comment by acieroid** [comment]
After some investigation, it seems that:
  - it seems to apply to all reporters: the lcov reporter is not containing information on the else branch. Similarly for the json reporter (the branch coverage is described is `[1]` rather than `[1, 0]`).
  - it does *not* apply to `istanbul-lib-instrument`: there is already a test for implicit else (first test of `if.yaml`), and it correctly produces `[1, 0]` as coverage

It seems that either the branch coverage gets modified between the instrumentation and the reporter, or that the reporter does not use info from the instrumentation?

I'm not familiar with the structure of this project, in case some guidance can be provided, I'd be happy to investigate further. Currently, I don't know where to look for the actual problem.

**Comment by AriPerkkio** [comment]
@antch + @acieroid, the `karma-coverage` used by angular seems to be using `istanbul-lib-source-maps`. That one does not preserve the implicit else. Exactly as described above - `istanbul-lib-instrument` is able to generate uncovered branch for implicit else, but once mapped back to sources through `istanbul-lib-source-maps`, the non-existing branch is lost. This will be fixed by #706.
